api_key: 'API Key'
domain: 'sandbox0709ef57f7c24b06adc26a69bd407cbf.mailgun.org'
username: 'postmaster@sandbox0709ef57f7c24b06adc26a69bd407cbf.mailgun.org'
password: '735b6c94d3f9420f629854421a5f596d-060550c6-1e938acc'
gmail_username: 'username@gmail.com'
gmail_password: 'gmail password'
